### PR TITLE
Fix floating-point precision

### LINKED ISSUE #27: Convert from using floating point to decimal
It seems that Elixir has issues with floating point number arithmetic. For example:
```elixir
iex(2)> 144.23 - 112.0
32.22999999999999
```

The expected result would instead be 32.23. There are some parts of the codebase (e.g. difficulty calculation, utxo amount calculation, fee calculation) that would suffer from such precision errors. Lets move to [this library](https://github.com/ericmj/decimal) instead and use that for the more precision-critical parts of the codebase.

### PR DESCRIPTION
**Pull request by Zac-Garby**
This pull request changes the calculations on transactions to use the `Decimal` type from the Decimal library, instead of primitive Elixir floats, to improve precision of transactions.

Parts of the other repositories will have to be changed: certainly the wallet app and probably the miner app too.

Fixes #27

### CODE REVIEW

File: lib/block.ex [hunk 1]
```diff
@@ -2,6 +2,7 @@ defmodule UltraDark.Blockchain.Block do
   alias UltraDark.Blockchain.Block
   alias UltraDark.Utilities
   alias UltraDark.Transaction
+  alias Decimal, as: D
```
Comment (alexdovzhanyn) [inline lib/block.ex]: lets use this library as 'Decimal' instead of 'D', as its not as descriptive of whats happening

File: lib/validator.ex [hunk 2]
```diff
@@ -79,7 +80,7 @@ defmodule UltraDark.Validator do
   end
 
   defp appropriate_coinbase_output?([coinbase | transactions], block_index) do
-    if Block.total_block_fees(transactions) + Block.calculate_block_reward(block_index) == List.first(coinbase.outputs).amount, do: :ok, else: {:error, "Coinbase output is invalid"}
+    if D.equal?(D.add(Block.total_block_fees(transactions), Block.calculate_block_reward(block_index)), List.first(coinbase.outputs).amount), do: :ok, else: {:error, "Coinbase output is invalid"}
```
Comment (alexdovzhanyn) [inline lib/validator.ex]: since we're nesting this logic inside of a function call now, it might make sense to set a new variable `total_fees = Block.total_block_fees(transactions)`, and using that in the comparison, just to make the code more readable

File: test/block_test.exs [hunk 3]
```diff
@@ -74,37 +76,34 @@ defmodule BlockTest do
...
+          %{txoid: "atxoid", amount: D.new(14)},
         ]
       }
     ]
 
-    # TODO -- we need to represent shades as decimal instead of float because of
-    # float arithmetic precision errors in the stdlib
-
-    # assert Block.total_block_fees(transactions) ==
+    assert D.equal? Block.total_block_fees(transactions), D.new(158.23)
```
Comment (alexdovzhanyn) [inline test/block_test.exs]: nice! you added the test :) :+1:

File: lib/block.ex (hunk 1 above)
Comment (Zac-Garby) [reply lib/block.ex]: That'd make a lot of the code really verbose. Also, the documentation of the library suggests you alias the library as `D`

Comment (alexdovzhanyn) [reply lib/block.ex]: Fair enough. Could you update with the other comment I made? It'll be ready for merge once that happens

Comment (Zac-Garby) [reply lib/block.ex]: Okay, I've done that now

**Comment by alexdovzhanyn** [comment]
Looks good, I'll test tonight
